# Generated by Django 5.2.1 on 2025-06-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bono #1', max_length=100)),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commercial_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('issue_date', models.DateField()),
                ('years_number', models.DecimalField(decimal_places=2, max_digits=2)),
                ('coupon_frequency', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('interest_rate_type', models.CharField(choices=[('efectiva', 'Efectiva'), ('nominal', 'Nominal')], max_length=10)),
                ('capitalization', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('annual_discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('income_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('premium_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('structuring_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('placement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('float_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cavali_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
