# Generated by Django 5.2.1 on 2025-06-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_alter_bond_cavali_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='years_number',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
