# Generated by Django 5.2.1 on 2025-06-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_alter_bond_years_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='cavali_type',
            field=models.CharField(choices=[('emisor', 'Emisor'), ('bonista', 'Bonista'), ('ambos', 'Ambos')], default='emisor', max_length=10),
        ),
        migrations.AddField(
            model_name='bond',
            name='float_type',
            field=models.CharField(choices=[('emisor', 'Emisor'), ('bonista', 'Bonista'), ('ambos', 'Ambos')], default='emisor', max_length=10),
        ),
        migrations.AddField(
            model_name='bond',
            name='placement_type',
            field=models.CharField(choices=[('emisor', 'Emisor'), ('bonista', 'Bonista'), ('ambos', 'Ambos')], default='emisor', max_length=10),
        ),
        migrations.AddField(
            model_name='bond',
            name='structuring_type',
            field=models.CharField(choices=[('emisor', 'Emisor'), ('bonista', 'Bonista'), ('ambos', 'Ambos')], default='emisor', max_length=10),
        ),
    ]
