# docker-compose.yml (CORREGIDO)
services:
  web:
    build: .
    command: gunicorn InverBono.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - sqlite_data:/app/InverBono/data
    ports:
      - "8000:8000"
    
volumes:
  sqlite_data: